### ISSUE TITLE
Not Working with Login - 404 Error

### ISSUE THREAD

**Issue by 91Abdullah** [ZiZuu-store/zzCleanURLs#13]
When click on sign in it displays 404 error unless we remove ?back-my-account from URL http://127.0.0.1:8088/prestashop/en/login?back=my-account

**Comment by ZiZuu-store** [comment]
Hi, thanks for reporting. 
Please provide more info to try to reproduce 

- PS version
- module version/branch
- languages/shops configuration

**Comment by 91Abdullah** [comment]
PrestaShop version: 1.6.0.14
Module version: Release 0.10.0 (stable)
Languages: 2 (en/ur) | {ur = Urdu}
Shop: 1 (no multishop)

**Comment by 91Abdullah** [comment]
Sorry for inconvenience. Module is working correctly, I wrongly installed forked version! Sorry for inconvenience once again.

Thanks for such a nice contribution (Y)

**Comment by 91Abdullah** [comment]
Closing.

**Comment by ZiZuu-store** [comment]
:) have a nice WE
