### ISSUE TITLE
Route to CMS category gives 404 error

### ISSUE THREAD

**Issue by devdesco-ceo** [ZiZuu-store/zzCleanURLs#20]
Using it with PS 1.6.1.2. Everything works just fine, as I see, but the "Route to CMS category" with suggested "info/{rewrite}/" gives 404 error on all CMS category links. Please look into this issue!!!

**Comment by ZiZuu-store** [comment]
Hi,
 thank you for your report. Will inspect and fix as soon as possible

**Comment by ZiZuu-store** [comment]
@devdesco-ceo can you confirm that on PS <1.6.1.2 it was working fine?!

**Comment by devdesco-ceo** [comment]
I just started developing under 1.6.1.2

**Comment by ZiZuu-store** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;26aQEvx8&#x2F;4-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test</a>

**Comment by ZiZuu-store** [comment]
@devdesco-ceo fixed on **release 1.0.1**

Thank you for your contribution

**Comment by devdesco-ceo** [comment]
Thanks a lot for maintaining the module! Confirming, it is working properly now!

**Comment by ZiZuu-store** [comment]
:+1:
