### ISSUE TITLE
Manufacturer URLs generate 404 error

### ISSUE THREAD

**Issue by devdesco-ceo** [ZiZuu-store/zzCleanURLs#24]
Manufacturer URLs generate 404 error with Friendly URLs enabled:

/index.php?controller=manufacturer&id_lang=1&id_manufacturer=0 works just fine...
/manufacturers/blablabla gives 404 error

In the Module settings is the following: "brands/{rewrite}" :(

Please see images attached...

![image 5](https://cloud.githubusercontent.com/assets/8983883/11322830/ac7f4508-90c3-11e5-9845-d6889369e4fe.png)
![image 6](https://cloud.githubusercontent.com/assets/8983883/11322831/ac80b438-90c3-11e5-99aa-91a9a6851818.png)
![image 7](https://cloud.githubusercontent.com/assets/8983883/11322841/f86e3578-90c3-11e5-92f5-575b3e68ad3c.png)

**Comment by ZiZuu-store** [comment]
Hi,
 please report your PS and module versions.

Will investigate asap 

Thanks for your feedback

**Comment by ZiZuu-store** [comment]
@devdesco-ceo is suppliers working fine instead??

**Comment by devdesco-ceo** [comment]
I do not have suppliers enabled. PS 1.6.1.2, latest updated zzCleanURLs

**Comment by ZiZuu-store** [comment]
OK started working on ..  each manufacturer is now working on https://github.com/ZiZuu-store/zzCleanURLs/tree/fix-manufacturer-supplier .. still have to fix the manufacturers/ listing
