### ISSUE TITLE
.html in categories URL generate 404

### ISSUE THREAD

**Issue by kibiribi** [ZiZuu-store/zzCleanURLs#25]
thanks for zzCleanURL!
ZiZuu Clean URLs v1.0.1 - от ZiZuu Store
it works fine for products!

but it doesn't work fine for categories in my case ( PrestaShop 1.6.1.1 - 1 shop, 1 language)

I've changed in SEO section: 
----------------------
Cache is turned on with compilation
Friendly URL is turned on 
path for products = products/{rewrite}.html - works fine
path for CMS = pages/{rewrite}.html - works fine

path for categories = catalog/{rewrite}.html - show me 404 :-(

According to recommendations:
Clear Smarty cache - DONE
Preferences -> SEO and URLs -> Set userfriendly URL off -> DONE
Preferences -> SEO and URLs -> Set userfriendly URL on -> DONE

but categories still show me 404 

Could you advise, what's wrong ?

**Comment by kibiribi** [comment]
some results from tests  - SEO category settings
-------------
catalog/{rewrite}.html/ - doesn't work
catalog/{rewrite}/ it works
catalog/{rewrite} it works

**Comment by kibiribi** [comment]
Any chance to fix this issue ? :-(
I tried to replace html  in CategoryController.php
as you did in product - 
-----ProductController.php----------
$sql = 'SELECT `id_product`
                FROM `'._DB_PREFIX_.'product_lang`
                WHERE `link_rewrite` = \''.pSQL(str_replace('.html', '', $product_rewrite))
------------------
but it doesn't work for link - www.site.com/category/folder.html 

WHERE `link_rewrite` = \''.pSQL(str_replace('.html', '',$category_rewrite))

**Comment by ZiZuu-store** [comment]
Hi @kibiribi 
  sorry for late reply ..  This behaviour is not supported, I'll see if I can implement it .. but I can't do it high priority

**Comment by kibiribi** [comment]
Thanks for reply. I understand. :-) 
I found paid module for this. By the way,
just in case - 
 I found 3 paid modules like yours, only one module supports category format - /category/some-text.html  
Category support - will be real advantage for this project in future... :-)

**Comment by ZiZuu-store** [comment]
I'll implement it asap .. it's not hard to do .. but I can't right now ;)

Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by ZiZuu-store** [comment]
@kibiribi Now we support html on every page ;)
