### ISSUE TITLE
Accented URL -> Category

### ISSUE THREAD

**Issue by metacreo** [ZiZuu-store/zzCleanURLs#32]
If Accented URL enabled and category contain cyrilic chars... on category page got 404

**Comment by ZiZuu-store** [comment]
Hi @metacreo 
  Thank you for your report.
Can you please clarify the following?

- the issue is only for category (product, cms,etc are ok) ? 
- please provide a sample category name to be used to reproduce
- is the same name working on PS without the module?
- PS version
- module version

Thanks

**Comment by metacreo** [comment]
I think only on category. Because product page showing ok. On cms pages not tested.
Examples of names:
example.com/en/turbochargers
example.com/ru/турбокомпрессоры
----------
example.com/en/equipment
example.com/lt/įranga
example.com/ru/оборудование
-------
The same names on PS with ID working ok.
Tested on prestashop 1.6.1.2

unfortunately now I do not have access to the files and I can not describe in detail.
Soon I try to repeat everything in a clean installation

**Comment by ZiZuu-store** [comment]
OK thank you .. will inspect ASAP

**Comment by metacreo** [comment]
Hi Zizuu,
fresh install of latest version.
CMS pages the same not work.
You can check at http://test.newestvision.com
BO conn:  /adminka
admin@newestvision.com
admin123
Thank You

**Comment by ZiZuu-store** [comment]
@metacreo oh wonderful thank you .. if you could gimme a console access to this test server I'll try to debug and fix in real time ASAP ;)

In case you can, please contact me via gitter or email for access credentials, thanks again

**Comment by ZiZuu-store** [comment]
@metacreo I'm debugging and working both on your test server and on my own 

On my server (PS 1.6.1.1) I installed the russian language and added a CMS page for it .. coping the name from your site (`ru/info/доставка`) .. on my server it works!! ..

Can be a PHP version issue?

**Comment by metacreo** [comment]
root@newestvision:/etc/systemd/system# php -v
PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by metacreo** [comment]
I can give you ssh access to server tomorrow.

**Comment by metacreo** [comment]
I found some info http://doc.prestashop.com/display/PS16/Handling+special+characters+in+links
maybe the problem in link constructor.

**Comment by ZiZuu-store** [comment]
@metacreo no need for xdebug for now .. a shell access should suffice at the moment 

thank you

**Comment by ZiZuu-store** [comment]
@metacreo good catch! I think the doc you found could be the issue .. even if I don't understand why it seems to work on my server even without any change ..

**Comment by ZiZuu-store** [comment]
On my server Cylillic seems to be correctly handled by PHP without any modification.

Please try to run the following:
```
webmaster@zz01$ php -r "\$uri = '/ru/оборудование'; \$uri = basename(\$uri); echo \$uri.\"\\n\"; preg_match_all('/[_a-zA-Z0-9\pL\pS-]/', \$uri, \$m); var_dump(\$m);"

оборудование
array(1) {
  [0]=>
  array(17) {
    [0]=>
    string(1) "�"
    [1]=>
    string(1) "�"
    [2]=>
    string(1) "�"
    [3]=>
    string(1) "�"
    [4]=>
    string(1) "�"
    [5]=>
    string(1) "�"
    [6]=>
    string(1) "�"
    [7]=>
    string(1) "�"
    [8]=>
    string(1) "�"
    [9]=>
    string(1) "�"
    [10]=>
    string(1) "�"
    [11]=>
    string(1) "�"
    [12]=>
    string(1) "�"
    [13]=>
    string(1) "�"
    [14]=>
    string(1) "�"
    [15]=>
    string(1) "�"
    [16]=>
    string(1) "�"
  }
}
```

**Comment by metacreo** [comment]
root@newestvision:~# php -r "\$uri = '/ru/оборудование'; \$uri = basename(\$uri)                               ; echo \$uri.\"\\n\"; preg_match_all('/[_a-zA-Z0-9\pL\pS-]/', \$uri, \$m); var_d                               ump(\$m);"
оборудование
array(1) {
  [0]=>
  array(17) {
    [0]=>
    string(1) "▒"
    [1]=>
    string(1) "▒"
    [2]=>
    string(1) "▒"
    [3]=>
    string(1) "▒"
    [4]=>
    string(1) "▒"
    [5]=>
    string(1) "▒"
    [6]=>
    string(1) "▒"
    [7]=>
    string(1) "▒"
    [8]=>
    string(1) "▒"
    [9]=>
    string(1) "▒"
    [10]=>
    string(1) "▒"
    [11]=>
    string(1) "▒"
    [12]=>
    string(1) "▒"
    [13]=>
    string(1) "▒"
    [14]=>
    string(1) "▒"
    [15]=>
    string(1) "▒"
    [16]=>
    string(1) "▒"
  }
}

**Comment by ZiZuu-store** [comment]
@metacreo Please join https://gitter.im/ZiZuu-store/zzCleanURLs to have a better interaction

**Comment by metacreo** [comment]
Resolved very simply 
Localization ->  Advanced:

Language identifier: en
Country identifier: gb   (!!! if lt or ru or other... rewrite not work!)

but it is strange why the work without the module

**Comment by ZiZuu-store** [comment]
Good to know :)

I think because without the module PS retrieves the object from DB just using the ID in the url, discarding the eventually malformed part of the string

Thank you for your time .. have a nice day
