### ISSUE TITLE
Fatal error on installation

### ISSUE THREAD

**Issue by DummeDitte** [ZiZuu-store/zzCleanURLs#33]
I'm trying to install this module - but I get and blank white page with nothing but this on it:

"[PrestaShop] Fatal error in module zzcleanurls:
Call to undefined method zzCleanUrls::displayWarning()"

What on earth am I doing wrong?

(Yes, it is the zzcleanurls.zip I'm installing)

**Comment by ZiZuu-store** [comment]
@DummeDitte .. As far as I can see .. nothing ... can you please report the following info?

- PS version
- other modules installed having their own overrides?
- zzCleanURLs version you downloaded
- double check the modules dir permissions

**Comment by ZiZuu-store** [comment]
same as #23

**Comment by DummeDitte** [comment]
Turns out it actually was installed despite the "Fatal error".

But it destroyed my "SEO & URLs" - whenever I turned the friendly URLs on, the site went down with a "Redirection loop"-error.
Now I've cleaned everything up following your guide in Readme, and my shop is back to normal.

I'll try installing the module once again.

FTR:
I'm running PS 1.6.0.8
Trying to install latest stable release, 1.0.3
Don't have any other overriding modules - as far as I know or can tell
Which permissions would I be looking for?

And yes, I se that it is the same issue as #23 - but that didn't really come with a solution either...

**Comment by DummeDitte** [comment]
Update:
Ok, I still get the error upon installation and if I try to configure the module.
But otherwise the module has been installed and is apparently working.

EXCEPT! My CMS-pages can't be reached. They return 404-errors.

**Comment by DummeDitte** [comment]
Oh, nope - now I fixed it!
(Without knowing how, but never the less).

Closing this issue. Thanks for responses! :)

**Comment by ZiZuu-store** [comment]
@DummeDitte   no chance to guess the reason of the problem? Just for reference for other users :)

Thanks

**Comment by DummeDitte** [comment]
Well - I changed the path from info/{id}-{rewrite} to content/{id}-{rewrite} and then back to info/{rewrite} and then links started working again. Maybe it was only a matter of caching or updating the .htaccess file? I don't know...

**Comment by ZiZuu-store** [comment]
OK it could be something related to caching .. thank you so much.
