### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by rafaviana** [ZiZuu-store/zzCleanURLs#36]
I'm getting a 404 error on categories pages... Can you help me?
PS version: 1.6.1.2

**Comment by rafaviana** [comment]
I'm using PS 1.6.1.2

**Comment by ZiZuu-store** [comment]
Please give more infos 

every category? describe your installation and if possible give us a live example

**Comment by rafaviana** [comment]
Could you please give me your IP so I can add you to see my website?

The url is: www.temosonline.com

**Comment by ZiZuu-store** [comment]
Hi,
 could you set a user/password auth instead?

We do not use a fixed IP

**Comment by rafaviana** [comment]
I bought a paid module and fixed the problem. Thank you anyway

**Comment by ZiZuu-store** [comment]
I'll be grate if you can tell us if you got the error on every category or only on some specific category .. thanks

**Comment by rafaviana** [comment]
I've installed your module again and uninstalled the paid module so you can see what's wrong. Category pages is working now, but product pages and cart/login and other pages don't

**Comment by ZiZuu-store** [comment]
you can write me ad info<AT>zizuu.com  thanks
