### ISSUE TITLE
{id} or {ean13} in product url

### ISSUE THREAD

**Issue by mikecc444** [ZiZuu-store/zzCleanURLs#41]
Is it possible to add product {id} or {ean13} or other fields to the product URL using SEO and URL settings?

If I change {categories:/}{rewrite}.html to {categories:/}{rewrite}-{id}.html for example, the url is generated ok but the accessing it gives 404.

**Comment by ZiZuu-store** [comment]
The goal of this module is to **remove** the id from the URL ... URLs with  ID are the default, if you want them you don't need this module. 

Or am I missing something?!

**Comment by mikecc444** [comment]
I need to remove the id only from category url, not from product urls. I hoped I can use your module to do this. If this is not posible I will try another solution.

Thanks!

Căpruciu Mihai

Teonic srl | Feronerii si accesorii pentru mobilier

RO-10714902 - J38/289/1998
UNICREDIT TIRIAC BANK RM.VÂLCEA
IBAN: RO70BACX0000004567081000

22 Gib Mihăescu, RO-240574
Râmnicu Vâlcea, Vâlcea, România
T: +40 250 730870 
F: +40 250 739973 
M: +40 747 491402

W: www.teonic.ro
W: www.feroshop.ro

**Comment by ZiZuu-store** [comment]
Uhmm it should be possible .. will inspect ASAP

**Comment by ZiZuu-store** [comment]
Using **ean13** instead of **id** doesn't work ?

**Comment by mikecc444** [comment]
No, also 404. .

**Comment by ZiZuu-store** [comment]
Ok

**Comment by mikecc444** [comment]
I think I found the problem, from what I see, the friendly URLS are not generated correctly after adding {id} in seo settings. My current product route is: **{categories:/}{rewrite}-{id}.html**, but the saved friendly url from the database does not contain the "-{id}" part. For example: this generated url **http://localhost/scule-si-unelte/burghie-precizie/freza-uluc-30mm-82233011-1.html** is saved as **freza-uluc-30mm-82233011** instead of **freza-uluc-30mm-82233011-1** where 1 is the product id.

This is why **isProductLink** function does not return true for product urls.

I changed line 124 from dispatcher to 

WHERE `link_rewrite` = \''.pSQL(basename(**substr($short_link,0,strripos($short_link,"-"))**, '.html')).'\' AND `id_lang` = '.(int)Context::getContext()->language->id;

Do you think this is the right solution ?

Thanks!

**Comment by ZiZuu-store** [comment]
Uhmm this way only work for your particular case in which you have chosen
to add the ID in this particular way ..

This can be a solution for you until we fix in a more general way ;)

Good work anyway

Il venerdì 22 gennaio 2016, mikecc444 <notifications@github.com> ha scritto:

> I think I found the problem, from what I see, the friendly URLS are not
> generated correctly after adding {id} in seo settings. My current product
> route is: *{categories:/}{rewrite}-{id}.html*, but the saved friendly url
> from the database does not contain the "-{id}" part. For example: this
> generated url *http://localhost/scule-si-unelte/burghie-precizie/freza-uluc-30mm-82233011-1.html
> <http://localhost/scule-si-unelte/burghie-precizie/freza-uluc-30mm-82233011-1.html>*
> is saved as *freza-uluc-30mm-82233011* instead of
> *freza-uluc-30mm-82233011-1* where 1 is the product id.
>
> This is why *isProductLink* function does not return true for product
> urls.
>
> I changed line 124 from dispatcher to
>
> WHERE link_rewrite = \''.pSQL(basename(
> *substr($short_link,0,strripos($short_link,"-"))*, '.html')).'\' AND
> id_lang = '.(int)Context::getContext()->language->id;
>
> Do you think this is the right solution ?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/zzCleanURLs/issues/41#issuecomment-173996359>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by ZiZuu-store** [comment]
OK, close to have a solution .. found a PrestaShop bug causing the problem

Will release a new version fixing the issue and will open a bug report to PS in order to have it fixed in a more structural way

Still a bit of patience please

**Comment by ZiZuu-store** [comment]
Made a pull request on PS1.6.x .. the same fix was already applied in the development branch, so it should be a good fix. 

**PrestaShop/PrestaShop#4991**

**Comment by ZiZuu-store** [comment]
@mikecc444 can you please try https://github.com/ZiZuu-store/zzCleanURLs/tree/fix-id-ean13 ??

Product should be fixed .. I'm working on categories and other .. please let me know if it works for you (what PS version)

**Comment by mikecc444** [comment]
yes it works, ps 1.6.1.3
thanks
