### ISSUE TITLE
ZiZuu Clean URLs Conflict with AgileMultiSeller

### ISSUE THREAD

**Issue by miguelbambo** [ZiZuu-store/zzCleanURLs#43]
Hi,

You module has conflict with AgileMultiSeller Module. How to bypass this? I like both.
See image attached.
![error override2](https://cloud.githubusercontent.com/assets/17058143/12830266/0b408918-cb97-11e5-8440-93f89de0ec97.jpg)

**Comment by ZiZuu-store** [comment]
Ho @miguelbambo 
  Unfortunately override modules have the risk to act on the same code of others ..

Will see if we can avoid to override the constructor .. but can't assure a deadline

**Comment by miguelbambo** [comment]
Hi,
Thank you for your prompt response. Can I share with you AgileMultiseller Module to help you overriding constructor or it is not necessary? If yes, send me your email.

Regards.
Miguel Bambo.

**Comment by ZiZuu-store** [comment]
It's not necessary. Thanks :)

**Comment by ZiZuu-store** [comment]
@miguelbambo I'm gone back into my module history and realised what I forgot .. I had to introduce the `__construct()` override to bypass a PS bug in module install/uninstall 

The constructor override is not necessary for this module to work, but it is the only way I found to have the `$default_rutes` property being set without rising a bug in the module uninstallation fase .. this bug would leave PS in an inconsistent state, not correctly removing the Dispatcher override.

If you PS version is not affected by this issue (I don't know if they fixed it and when) you can safely remove the constructor override and simply declare the property in the class body ..

**Comment by miguelbambo** [comment]
@ZiZuu-store 
Thanks for remembering my issue.
I use Prestashop Version 1.6.0.14 (What do you say about it, if you know some?)
Do I need to upgrade to the latest version?
I am not sure with your tips.

Regards.

**Comment by ZiZuu-store** [comment]
I tried the module on PS 1.6.0.14 and I had to use the construct on that version .. don't know if current version still has the problem .. I'll try to give a try in the next days on a test server

**Comment by miguelbambo** [comment]
Ok thanks.

**Comment by ZiZuu-store** [comment]
Unfortunately PS isn't able to handle multi line class properties during the module's override remove process (see https://github.com/PrestaShop/PrestaShop/blob/1.6.1.4/classes/module/Module.php#L2978 )

I'm trying to find a patch to submit to PS dev team, but it is a bit complicated to do a clean job .. will keep on trying

**Comment by miguelbambo** [comment]
Thank you very much for your endeavour.
Good job.
Hope they will be a solution.

**Comment by ZiZuu-store** [comment]
Please tell me if the conflicting module is overriding loadRoutes() too

**Comment by miguelbambo** [comment]
Hmmm. . .  Sorry! I dont know how to check that. Please, guide me on how to
check that. I am available to colaborate.

**Comment by ZiZuu-store** [comment]
Once you have the other module being installed look at PS_ROOT_DIR/`override/classes/Dispatcher.php`and paste it here .. thanks

**Comment by miguelbambo** [comment]
Ok. Wait for some minutes because your module destroy my Prestashop files
on localhost so I need to reinstall Prestashop on localhost and also
install Agile modules and check that.
See you soon.
Thanks.

**Comment by ZiZuu-store** [comment]
Uh .. what does "my module destroy PS" .. it should absolutely not !

**Comment by miguelbambo** [comment]
I mean, after the error report appears after trying to install your module
automatically I am unable to access to my prestashop website or phpmyadmin
on localhost i return it gives me just a white empty page.
Firstly, I didnt notice it was related to your module conflict with Agile
and ive tried to change the Port thinking on that issue with skype and
other related programs but after new prestashop reinstallation everything
went very well without trouble. So my conclusion:
The conflict between your module and Agile Multiseller/Multishop during
installation of your module leads to corruption of my prestashop files even
if the installation be incomplete.

I can be wrong but its whats it seems to be.

**Comment by miguelbambo** [comment]
Alright, I have some idea.
I will go to that file even being unable to access to localhost , I will paste it right now.

**Comment by miguelbambo** [comment]
<?php
class Dispatcher extends DispatcherCore
{
	/*
	* module: agilemultipleseller
	* date: 2016-02-04 23:00:57
	* version: 3.1.0.1
	*/
	protected function __construct()
	{
		if(Module::isInstalled('agilemultipleshop'))
		{
			include_once(_PS_ROOT_DIR_ ."/modules/agilemultipleshop/agilemultipleshop.php");
			$this->default_routes = array_merge($this->default_routes, AgileMultipleShop::get_rewrite_rules());			
		}
		if(Module::isInstalled('agileshowcasemanager'))
		{
			include_once(_PS_ROOT_DIR_ ."/modules/agileshowcasemanager/agileshowcasemanager.php");
			$this->default_routes = array_merge($this->default_routes, AgileShowcaseManager::get_rewrite_rules());			
		}
		
		parent::__construct();
	}	
	
	
	/*
	* module: agilemultipleseller
	* date: 2016-02-04 23:00:57
	* version: 3.1.0.1
	*/
	public function createUrl($route_id, $id_lang = null, array $params = array(), $force_routes = false, $anchor = '', $id_shop = null)
	{
		
		global $link;
		if($route_id =="agilesellers")
		{
			return $link->getAgileSellersLink(Tools::getValue('filter'),$id_lang, Tools::getValue('loclevel'), Tools::getValue('parentid'));
		}
		if($route_id =="sellerlocation")
		{
			return $link->getSellerLocationLink(Tools::getValue('$id_location'), Tools::getValue('location_level'), NULL, $id_lang);
		}
		if($route_id =="sellercountry")
		{
						return $link->getSellerCountryLink(Tools::getValue('id_seller_country'), NULL, $id_lang);
		}		
		
		return parent::createUrl($route_id, $id_lang, $params, $force_routes, $anchor);
	}
}

**Comment by ZiZuu-store** [comment]
OK I should be able to provide a compatible rewrite .. hoping not breaking anything else .. stay tuned

**Comment by miguelbambo** [comment]
Ok thanks.

**Comment by ZiZuu-store** [comment]
Please try if https://github.com/ZiZuu-store/zzCleanURLs/tree/avoid-contructor-override works for you ..

**Comment by miguelbambo** [comment]
Ok I am trying right now.

**Comment by miguelbambo** [comment]
Sorry no power here since now, my computer will shut down :( I will let you
know as soon as the power comes back.

**Comment by miguelbambo** [comment]
I can upload the module but doesnt appear to be installed in the modules list.

**Comment by miguelbambo** [comment]
See image.
![construct2](https://cloud.githubusercontent.com/assets/17058143/12934948/d916dd18-cf9a-11e5-965b-f317d5bd26e6.jpg)
![construct](https://cloud.githubusercontent.com/assets/17058143/12934949/d917de34-cf9a-11e5-9fe2-9f5c78881218.jpg)

**Comment by miguelbambo** [comment]
![routes](https://cloud.githubusercontent.com/assets/17058143/12935381/fd981a5a-cf9d-11e5-844c-f95fee5771d0.jpg)
![routes2](https://cloud.githubusercontent.com/assets/17058143/12935382/fd9ce422-cf9d-11e5-905a-d2b0da3ab907.jpg)

**Comment by ZiZuu-store** [comment]
How do you installed the development branch of the module?

you have to assure taht the module dir is `zzcleanurls` (lowercase, as I wrote) .. 

Alternatively you can just install the "stable" version and then replace the file `override/classes/Dispatcher.php` with the one taken from the development branch .. then reset the module

**Comment by ZiZuu-store** [comment]
Anyway .. I tested the new approach and it works fine.. 

As overriding `loadRoutes()` should have less conflicts with other modules I think this fix can be considered the right way to do things. 

I'm going to deploy a new official stable release having this fix enabled. Just install the new release and go ahead :)

Thank you for your report @miguelbambo

**Comment by miguelbambo** [comment]
Hi @ZiZuu-store,
Thank you.
Yes maybe the problem was to not rename the folder, I used as it was : 
zzCleanURLs-avoid-contructor-override.zip instead of renaming it to "zzcleanurls" as you teach right now.
I will let you know later after re-test it.

Thank you very much.

**Comment by ZiZuu-store** [comment]
You are welcome 

Just install https://github.com/ZiZuu-store/zzCleanURLs/releases/tag/v1.0.4 :)

**Comment by miguelbambo** [comment]
Oops!
One little trouble - still conflicts with Agille.
See image.
![getcategorylink](https://cloud.githubusercontent.com/assets/17058143/12944344/1735632c-cfef-11e5-9e76-b6b0a6c96f0f.jpg)

**Comment by miguelbambo** [comment]
That is way I thought the best way maybe you could do some tests with Agile Modules while making some corrections in your module but I think we are almost there.
Thanks for being patient with my issue.

Regards.

**Comment by ZiZuu-store** [comment]
Sorry, I can't help you this time 

My module needs to override things to work, can't do anything to find a workaround 

Sorry

**Comment by miguelbambo** [comment]
Ooohhhh . . . What a pity for me!
That is ok.
One idea:
Can I delete the affected Agile Module File so it can be replaced by your file?
Does this seems logical?

**Comment by ZiZuu-store** [comment]
Let's continue on [Gitter](https://gitter.im/ZiZuu-store/zzCleanURLs)
