### ISSUE TITLE
[RFE] Use "-" instead of "/" as categories separator

### ISSUE THREAD

**Issue by janikjan** [ZiZuu-store/zzCleanURLs#46]
Hi,

now you are able only to have as separator between categories the slash "/". But for some cases nice will be if you can use as separator "-" instead only to use "/" .

So now the link looks like https://www.bezpopelniku.cz/elektronicke-cigarety/innokin
after modification it will looks like https://www.bezpopelniku.cz/elektronicke-cigarety-innokin

Thank you.

**Comment by ZiZuu-store** [comment]
It is a quite specific request .. will look if implement depending of the amount of work needed.

Thanks

**Comment by janikjan** [comment]
Thank you. This solution will also fix the issue in #44 because you will have only unique URLs :).

**Comment by ZiZuu-store** [comment]
:+1:  you are right, but #44 caveats still remains ..

**Comment by janikjan** [comment]
Yes #44 still remains for "/" as separator for categories and I think priority should be to fix #44 issue. This one is here is only maybe the second option which should work.

**Comment by ZiZuu-store** [comment]
Sorry but I don't think this request should be satisfied.
