### ISSUE TITLE
zzCleanURLs is not working on 1.6.1.4 (?)

### ISSUE THREAD

**Issue by ehsanatwork** [ZiZuu-store/zzCleanURLs#51]
Hi

At first i would like to thanks to you, for your nice work of Prestashop module "zzCleanURLs". 
I am trying to use this module on my Prestashop version 1.6.1.4.

After installing this module, i have made the essential changes under (seo & url --> schema of urls) that you mentioned on github. and according to the instructions, i have clear the cache.

But the problem is, when i make those parameter changes, it shows some errors such as "Keyword "{id}" required for route "product_rule" (rule: "{category:/}{rewrite}.html")"

and when i clear the cache, the changes are not coming and come back the previous one again.

here is some screenshot.

http://prntscr.com/aa5hrq

http://prntscr.com/aa5hza

What should i do?

Thank You

**Comment by ZiZuu-store** [comment]
It seems the module is not installed ..

Please give me as many info as you can.
Il 02/mar/2016 08:50, "SMEHSAN" <notifications@github.com> ha scritto:

**Comment by ehsanatwork** [comment]
This is time this works.
Just amazing. 

Just one thing i want to know,

what about the Home inside the url.

http://prntscr.com/abefq5

how can i remove that?

Thank You

**Comment by ZiZuu-store** [comment]
What is home?

Nothing in this module add a home path. So it has to be related to you categories or CMS configuration I suppose

**Comment by ZiZuu-store** [comment]
@ehsanatwork .. ping :)

**Comment by dmitrymurashenkov** [comment]
Run into the same issue. Seems a single step should be added to installation guide:

After module is uploaded it is not installed by default (at least in Presta 1.6.1.4), but simply added to list of available module, so you have to find there and click "install" there.

After that it works fine.

**Comment by ZiZuu-store** [comment]
Will do .. thanks

**Comment by ZiZuu-store** [comment]
done https://github.com/ZiZuu-store/zzCleanURLs/blob/dev/README.md

Thanks

**Comment by maximo88** [comment]
It works perfect in 1.6.1.5. I am really impressed with your work. You have helped a lot of users for free. You deserve a prize.

**Comment by ZiZuu-store** [comment]
Thank you very much, I really appreciate your feedback :)

**Comment by Alexezi** [comment]
unfortunately not working for me :-( BO say: module uploaded successfully but I cant see it listed. In what name it shows up in Module section?

**Comment by drAlberT** [comment]
search for "faktiva" .. be sure you are not filtering modules somehow .. it could had been uploaded but not   installed as per the [comment above](https://github.com/faktiva/prestashop-clean-urls/issues/51#issuecomment-214331878).

**Comment by drAlberT** [comment]
@Alexezi news?

**Comment by Alexezi** [comment]
problem solved! Ive downloaded wrong version.
