### ISSUE TITLE
Extra & or / after URL

### ISSUE THREAD

**Issue by ajensen27** [ZiZuu-store/zzCleanURLs#52]
This module seems to work in that it puts the rel=canonical link in my pages but this is the second time I've installed it and it creates URL's for my site with an & or extra / after them. I can see this in Google Analytics. Any ideas why this might be happening?

**Comment by ajensen27** [comment]
I'm sorry but I can see now in the instructions that I have to have my schema of url's set up a certain way. Is this what was causing the issue?

Also, won't this affect my sites rankings in Google since I'd be changing the URL?

**Comment by ZiZuu-store** [comment]
Hi @ajensen27,
  sorry for late reply .. can you clarify your issue please? Can you provide more info about PS version, module version, a live example where I can see this issue ?

Thank you

**Comment by ZiZuu-store** [comment]
@ajensen27 any news?

**Comment by ajensen27** [comment]
I'm on PS 1.6.2 and it was the latest version of your module available here. I uninstalled your module and used this hack below to get canonical URL's and everything is working perfectly again (no issues with extra characters after my URL). I didn't need the other options so this is working fine for me. Thanks.

https://www.prestashop.com/forums/topic/420750-canonical-url-how-to-implement-in-16/

**Comment by ZiZuu-store** [comment]
- this module does not add any **canonical** tag
- latest Prestashop version available is 1.6.1.4 but you use **1.6.2** ?

This is an invalid issue. No enough neither pertinent info was given to be able to investigate a possible bug.
