### ISSUE TITLE
Blog module giving error

### ISSUE THREAD

**Issue by codepoppo** [ZiZuu-store/zzCleanURLs#58]
Hi- All other controllers work well with clean URL and no ID but not with the blog module. I checked the controller index for this module and it is written correctly. How do I correct this as SSL is failing and Google is knowing my score down? TY!
![clean url without id working](https://cloud.githubusercontent.com/assets/19863425/17528777/b2d1d7d8-5e3e-11e6-9086-27042f5caf27.jpg)
![url not friendly and has id](https://cloud.githubusercontent.com/assets/19863425/17528786/bc1521ec-5e3e-11e6-8116-57f74119314a.jpg)

**Comment by codepoppo** [comment]
ms Blog
*
*  @author    Joommasters <joommasters@gmail.com>
*  @copyright 2007-2015 Joommasters
*  @license   license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
*  @Website: http://www.joommasters.com
*/

include_once(_PS_MODULE_DIR_.'jmsblog/class/JmsBlogHelper.php');
class JmsblogCategoriesModuleFrontController extends ModuleFrontController
{
	public $ssl = true;
	public $display_column_left = false;

	/**
	 * @see FrontController::initContent()
	 */
	public function initContent()
	{
		
		parent::initContent();			
		$categories 	= $this->getCategories();		
		$jmsblog_setting = JmsBlogHelper::getSettingFieldsValues();
		for($i = 0; $i < count($categories); $i++)
		{
			$categories[$i]['introtext'] = JmsBlogHelper::genIntrotext($categories[$i]['description'], 120);			
		}
		$this->context->controller->addCSS($this->module->getPathUri().'views/css/style.css', 'all');				
		$this->context->smarty->assign(array('meta_title' => 'Categories'));
		$this->context->smarty->assign(array(
			'categories' => $categories,			
			'jmsblog_setting' => $jmsblog_setting,
			'image_baseurl' => $this->module->getPathUri().'views/img/'
		));
		$this->setTemplate('categories.tpl');

**Comment by ZiZuu-store** [comment]
Hi,
  thanks for reporting.

Sorry but I don't fully understand the issue. What is your PS configuration, the module configuration, the expected behaviour and the obtained one?

Have you other modules installed that are overriding the core?

How can I reproduce and test ?

**Comment by ZiZuu-store** [comment]
@codepoppo are you alive?
